# This is a basic workflow to help you get started with Actions

name: fast-build-dev-tools-action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: env prepare
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$(pwd)/depot_tools:$PATH
          echo $PATH
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH
          echo $(pwd)
      - name: Build
        run: |
          mkdir devtools
          cd devtools
          fetch devtools-frontend
          cd devtools-frontend
          gn gen out/fast-build --args='devtools_skip_typecheck=true'
          autoninja -C out/fast-build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-devtools-frontend-fast-build
          path: devtools/devtools-frontend/out/fast-build/gen/front_end
